//! RFB protocol message types and constants.
//!
//! Re-exported from the shared `vnc-protocol` crate.

pub use vnc_protocol::messages::{
    ClientMsgType, ServerMsgType, CLIENT_CUT_TEXT, CLIENT_ENABLE_CONTINUOUS_UPDATES, CLIENT_FENCE,
    CLIENT_FRAMEBUFFER_UPDATE_REQUEST, CLIENT_KEY_EVENT, CLIENT_POINTER_EVENT,
    CLIENT_SET_ENCODINGS, CLIENT_SET_PIXEL_FORMAT, FENCE_FLAG_BLOCK_AFTER, FENCE_FLAG_BLOCK_BEFORE,
    FENCE_FLAG_REQUEST, FENCE_FLAG_SYNC_NEXT, FENCE_MAX_PAYLOAD, RFB_VERSION, SERVER_BELL,
    SERVER_END_OF_CONTINUOUS_UPDATES, SERVER_END_OF_CONTINUOUS_UPDATES_LEGACY, SERVER_FENCE_LEGACY,
    SERVER_FRAMEBUFFER_UPDATE, SERVER_SERVER_CUT_TEXT, SERVER_SET_COLOUR_MAP_ENTRIES,
};
pub use vnc_protocol::security::{
    SecurityType, SECURITY_APPLE_DH, SECURITY_NONE, SECURITY_RSA_AES, SECURITY_RSA_AES256,
    SECURITY_TIGHT, SECURITY_VENCRYPT, SECURITY_VNC_AUTH,
};
pub use vnc_protocol::{framing, handshake, qemu, raw, server_init::ServerInit};

pub use crate::apple;
